/**
 *
 *  ContactsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "ContactsCtrl.h"
#include <string>





void ContactsCtrl::getOne(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback,
                          Contacts::PrimaryKeyType &&id)
{
    ContactsCtrlBase<>::getOne(req, std::move(callback), std::move(id));
}


void ContactsCtrl::updateOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Contacts::PrimaryKeyType &&id)
{
    ContactsCtrlBase<>::updateOne(req, std::move(callback), std::move(id));
}


void ContactsCtrl::deleteOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Contacts::PrimaryKeyType &&id)
{
    ContactsCtrlBase<>::deleteOne(req, std::move(callback), std::move(id));
}

void ContactsCtrl::get(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    ContactsCtrlBase<>::get(req, std::move(callback));
}

void ContactsCtrl::create(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    ContactsCtrlBase<>::create(req, std::move(callback));
}
