/**
 *
 *  ContactMessagesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ContactMessagesCtrlBase.h"

#include "ContactMessages.h"
using namespace drogon;

using namespace drogon_model::sqlite3;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the contact_messages table.
 */

class ContactMessagesCtrl: public drogon::HttpController<ContactMessagesCtrl>, public ContactMessagesCtrlBase<>
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(ContactMessagesCtrl::get,"/contactmessages",Get,Options,"LoginFilter");
    ADD_METHOD_TO(ContactMessagesCtrl::create,"/contactmessages",Post,Options,"LoginFilter");
    //ADD_METHOD_TO(ContactMessagesCtrl::update,"/contactmessages",Put,Options,"LoginFilter");
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
