/**
 *
 *  ContactMessagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "ContactMessagesCtrl.h"
#include <string>






void ContactMessagesCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    ContactMessagesCtrlBase<>::get(req, std::move(callback));
}

void ContactMessagesCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    ContactMessagesCtrlBase<>::create(req, std::move(callback));
}
