/**
 *
 *  MessagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "MessagesCtrl.h"
#include <string>





void MessagesCtrl::getOne(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback,
                          Messages::PrimaryKeyType &&id)
{
    MessagesCtrlBase<>::getOne(req, std::move(callback), std::move(id));
}


void MessagesCtrl::updateOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Messages::PrimaryKeyType &&id)
{
    MessagesCtrlBase<>::updateOne(req, std::move(callback), std::move(id));
}


void MessagesCtrl::deleteOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Messages::PrimaryKeyType &&id)
{
    MessagesCtrlBase<>::deleteOne(req, std::move(callback), std::move(id));
}

void MessagesCtrl::get(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    MessagesCtrlBase<>::get(req, std::move(callback));
}

void MessagesCtrl::create(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    MessagesCtrlBase<>::create(req, std::move(callback));
}
