/**
 *
 *  MessagesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "MessagesCtrlBase.h"

#include "Messages.h"
using namespace drogon;

using namespace drogon_model::sqlite3;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the messages table.
 */

class MessagesCtrl: public drogon::HttpController<MessagesCtrl>, public MessagesCtrlBase<>
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(MessagesCtrl::getOne,"/messages/{1}",Get,Options,"LoginFilter");
    ADD_METHOD_TO(MessagesCtrl::updateOne,"/messages/{1}",Put,Options,"LoginFilter");
    ADD_METHOD_TO(MessagesCtrl::deleteOne,"/messages/{1}",Delete,Options,"LoginFilter");
    ADD_METHOD_TO(MessagesCtrl::get,"/messages",Get,Options,"LoginFilter");
    ADD_METHOD_TO(MessagesCtrl::create,"/messages",Post,Options,"LoginFilter");
    //ADD_METHOD_TO(MessagesCtrl::update,"/messages",Put,Options,"LoginFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Messages::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Messages::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Messages::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
